### ISSUE TITLE
DLL for zarinpal

### ISSUE THREAD

**Issue by AminMhmdi** [ZarinPal-Lab/SampleCode-Csharp#1]
hi
i download sample code 
but there are no dll for reference

**Comment by amiri27** [comment]
There's no DLL at All.. It's just a simple webreference which is linked to ZarinPal Webservice address:

https://www.zarinpal.com/pg/services/WebGate/wsdl

Regards,

**Comment by AminMhmdi** [comment]
but i get error
Error	CS0246	The type or namespace name 'Zarinpal' could not be found (are you missing a using directive or an assembly reference?)
in below line
 Zarinpal.PaymentGatewayImplementationServicePortTypeClient zp = new Zarinpal.PaymentGatewayImplementationServicePortTypeClient();

**Comment by AminMhmdi** [comment]
how can i use code in asp.net mvc??

**Comment by amiri27** [comment]
Just add the above URL as webreference to your project like explained below:

http://www.c-sharpcorner.com/UploadFile/0c1bb2/consuming-web-service-in-Asp-Net-web-application/

Regards,

**Comment by AminMhmdi** [comment]
thank you so much
